Repository pc2ccs/pc2v9, pull requests merged in 2022-12, with the labels that each got.

#629 i628: ignore contest id that is received on PATCH - fixes #628
  src/edu/csus/ecs/pc2/services/web/ContestService.java
Labels: bug, high priority

#633 i632 - Send out "runs" events during a live contest - fixes #632
  src/edu/csus/ecs/pc2/core/execute/JudgementUtilites.java
  src/edu/csus/ecs/pc2/services/web/EventFeedStreamer.java
Labels: bug, high priority, In PR code review

#639 I564 support per problem output limit
  samps/contests/mini/config/contest.yaml
  samps/contests/mini/config/sumit/problem.yaml
  samps/contests/sumithello/config/contest.yaml
  samps/contests/sumithello/config/hello/problem.yaml
  samps/contests/sumithello/config/sumit/problem.yaml
  src/edu/csus/ecs/pc2/core/Constants.java
  src/edu/csus/ecs/pc2/core/execute/Executable.java
  src/edu/csus/ecs/pc2/core/execute/ProgramRunner.java
  src/edu/csus/ecs/pc2/core/imports/ContestXML.java
  src/edu/csus/ecs/pc2/core/model/ContestInformation.java
  src/edu/csus/ecs/pc2/core/model/Problem.java
  src/edu/csus/ecs/pc2/core/report/InternalDumpReport.java
  src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java
  src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java
  src/edu/csus/ecs/pc2/ui/ContestInformationPane.java
  src/edu/csus/ecs/pc2/ui/EditProblemPane.java
  src/edu/csus/ecs/pc2/ui/ProblemsPane.java
  test/edu/csus/ecs/pc2/core/model/ContestInformationTest.java
  test/edu/csus/ecs/pc2/core/model/ProblemTest.java
  test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java
Labels: enhancement

#637 i636: add junit test for getLastTestCaseArray - fixes issue #636
  test/edu/csus/ecs/pc2/core/execute/JudgementUtilitesTest.java
Labels: Small LOE
