Repository pc2ccs/pc2v9, pull requests merged in 2022-10, with the labels that each got.

#553 i552: Do not start shadowing, if clock stopped. Show message
  src/edu/csus/ecs/pc2/ui/ShadowControlPane.java
Labels: high priority

#555 I267 shadow GUI update delays
  samps/uiname.properties
  src/edu/csus/ecs/pc2/core/InternalController.java
  src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java
  src/edu/csus/ecs/pc2/ui/eventfeed/ServicesView.java
Labels: high priority, Shadow

#554 I 502 add skip sub project build
  build.xml
  package.xml
Labels: high priority

#471 I 450 add yaml load for account permissions
  samps/contests/tenprobs/config/contest.yaml
  src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java
  src/edu/csus/ecs/pc2/imports/ccs/PermissionYamlLoader.java
  test/edu/csus/ecs/pc2/core/model/SampleContest.java
  test/edu/csus/ecs/pc2/core/util/AbstractTestCase.java
  test/edu/csus/ecs/pc2/imports/ccs/PermissionYamlLoaderTest.java
Labels: high priority

#549 I429 shadow reconnect to primary - fixes #429
  src/edu/csus/ecs/pc2/shadow/IRemoteContestAPIAdapter.java
  src/edu/csus/ecs/pc2/shadow/IShadowMonitorStatus.java
  src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java
  src/edu/csus/ecs/pc2/shadow/RemoteContestAPIAdapter.java
  src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java
  src/edu/csus/ecs/pc2/shadow/ShadowController.java
  src/edu/csus/ecs/pc2/ui/ContestInformationPane.java
  src/edu/csus/ecs/pc2/ui/ShadowControlPane.java
Labels: high priority, Shadow

#563 i559: add some CLICS fields
  src/edu/csus/ecs/pc2/core/imports/clics/CLICSLanguage.java
  src/edu/csus/ecs/pc2/core/imports/clics/CLICSProblem.java
Labels: Small LOE

#568 Add execute substitution vars :infilename :ansfilename - fixes #567
  src/edu/csus/ecs/pc2/core/execute/Executable.java
Labels: high priority

#571 I 570 parsing errors and other contest compare fixes
  src/edu/csus/ecs/pc2/core/imports/clics/CLICSLanguage.java
  src/edu/csus/ecs/pc2/core/imports/clics/CLICSProblem.java
  src/edu/csus/ecs/pc2/core/imports/clics/CLICSStatement.java
  src/edu/csus/ecs/pc2/core/report/ContestCompareModel.java
  test/edu/csus/ecs/pc2/core/imports/clics/CLICSEventFeedEventTest.java
  testdata/CLICSEventFeedEventTest/event-feed.4probs.nljson
Labels: bug, high priority
