Repository pc2ccs/pc2v9, pull requests merged in 2023-11, with the labels that each got.

#834 I 833 upgrade WTI angular components
  .github/workflows/ci.yml
  projects/WTI-UI/angular.json
  projects/WTI-UI/package.json
  projects/WTI-UI/src/app/app.module.ts
  projects/WTI-UI/src/app/modules/clarifications/clarifications.module.ts
  projects/WTI-UI/src/app/modules/options/options.module.ts
  projects/WTI-UI/src/app/modules/runs/runs.module.ts
  projects/WTI-UI/src/app/modules/scoreboard/scoreboard.module.ts
  projects/WTI-UI/src/app/modules/shared/shared.module.ts
Labels: WTI-UI, WTI-API Server

#849 Change wording for interactive validator choice for Custom Output Validators
  src/edu/csus/ecs/pc2/ui/EditProblemPane.java
Labels: Small LOE, One Approval

#851 I850 - Validate that memory limit is non-negative in sandbox configuration for a problem
  src/edu/csus/ecs/pc2/ui/EditProblemPane.java
Labels: Small LOE, One Approval

#860 i859: update button titles and tool tips
  src/edu/csus/ecs/pc2/ui/QuickJudgePane.java
Labels: One Approval

#877 V9.10
  .github/workflows/ci.yml
  projects/WTI-UI/angular.json
  projects/WTI-UI/package.json
  projects/WTI-UI/src/app/app.module.ts
  projects/WTI-UI/src/app/modules/clarifications/clarifications.module.ts
  projects/WTI-UI/src/app/modules/options/options.module.ts
  projects/WTI-UI/src/app/modules/runs/runs.module.ts
  projects/WTI-UI/src/app/modules/scoreboard/scoreboard.module.ts
  projects/WTI-UI/src/app/modules/shared/shared.module.ts
Labels: One Approval
