Repository pc2ccs/pc2v9, pull requests merged in 2023-09, with the labels that each got.

#802 I801 Fix wrong units for CLICS per-problem output limit
  samps/contests/mini/config/sumit/problem.yaml
  src/edu/csus/ecs/pc2/core/Constants.java
  src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java
Labels: One Approval

#806 I805 Copy forgotten fields when loading accounts
  src/edu/csus/ecs/pc2/core/imports/LoadAccounts.java
Labels: One Approval

#814 i881: update scoreboard JSON to CLICS 2022-07
  src/edu/csus/ecs/pc2/core/imports/clics/CLICSContestState.java
  src/edu/csus/ecs/pc2/core/imports/clics/CLICSScoreboard.java
  src/edu/csus/ecs/pc2/core/report/ScoreboardJSONReport.java
Labels: One Approval

#812 I810 Make sure to kill off all processes in cgroup at start
  scripts/pc2_interactive.sh
  scripts/pc2sandbox.sh
  scripts/pc2sandbox_interactive.sh
Labels: high priority, NEXT Contest, One Approval

#813 I607 Interim fix for issue #607 "Add a compile time limit".
  scripts/dotimedcompile.sh
Labels: NEXT Contest
