Repository pc2ccs/pc2v9, pull requests merged in 2023-12, with the labels that each got.

#880 I878: Correct test data for results comparison
  test/edu/csus/ecs/pc2/core/report/FileComparisonUtilitiesTest.java
  testdata/FileComparisonUtilitiesTest/resultscompwork/results/pc2/scoreboard.json
Labels: Shadow, Small LOE

#894 I863 add team identification to wti UI
  projects/WTI-UI/src/app/app.module.ts
  projects/WTI-UI/src/app/modules/clarifications/components/clarifications-page/clarifications-page.component.ts
  projects/WTI-UI/src/app/modules/core/services/app-title.service.ts
  projects/WTI-UI/src/app/modules/login/components/login-page/login-page.component.ts
  projects/WTI-UI/src/app/modules/options/components/options-page/options-page.component.ts
  projects/WTI-UI/src/app/modules/runs/components/runs-page/runs-page.component.ts
  projects/WTI-UI/src/app/modules/scoreboard/components/scoreboard-page/scoreboard-page.component.ts
  projects/WTI-UI/src/app/modules/shared/components/app-header/app-header.component.html
  projects/WTI-UI/src/app/modules/shared/components/app-header/app-header.component.scss
  projects/WTI-UI/src/app/modules/shared/components/app-header/app-header.component.ts
Labels: enhancement

#899 i898: update sumithello sample contest to generate 2 scoreboard accts.
  samps/contests/sumithello/config/contest.yaml
Labels: good first issue, Small LOE, One Approval
