Repository pc2ccs/pc2v9, pull requests merged in 2024-03, with the labels that each got.

#928 i_927 Promote develop branch to Version 9.11build
  build.xml
Labels: One Approval

#923 add results.csv bits
  src/edu/csus/ecs/pc2/exports/ccs/ResultsFile.java
  src/edu/csus/ecs/pc2/ui/board/ScoreboardCommon.java
Labels: One Approval

#934 i933 Explicitly check for server when initializing for RunsTables
  src/edu/csus/ecs/pc2/ui/SelectJudgementFrame.java
Labels: Small LOE, One Approval

#936 i935 Fix incorrect string comparisons that caused shadow reconnects
  src/edu/csus/ecs/pc2/shadow/ShadowController.java
Labels: Small LOE, NEXT Contest, One Approval

#944 i_943 Fix Group tab on Edit Problem
  src/edu/csus/ecs/pc2/ui/ProblemGroupPane.java
Labels: One Approval

#947 i_946 Preserve problem title if no TEX files
  src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java
Labels: One Approval
